#!/bin/bash
#chkconfig: 3 99 85 
# pushserverd - Startup script for pushserver
# processname: pushserverd
. /etc/rc.d/init.d/functions
NODE="/usr/bin/node --nouse-idle-notification --max-new-space-size=2000000 --max-old-space-size=4000"
PUSH_SERVER="/opt/pdi/owd/push_server/src/"
CONFIGFILE="$PUSH_SERVER/config.js"
OPTIONS=" start.js"
PUSHSERVER_USER=push_server
PUSHSERVER_GROUP=push_server

start()
{
  echo -n $"Starting push_server..."
  echo
  cd $PUSH_SERVER
  nohup $NODE $OPTIONS >  /dev/null 2>&1 &
  RETVAL=$?
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/pushserverd
  sleep 2
  if [ -e /var/push.socket ]; then 
	chmod 777 /var/push.socket
  	sleep 1
  	[ `stat  /var/push.socket -c %a` -eq 777 ] && success || failure
  fi 
echo 
}

stop()
{
  echo -n $"Stopping push_server. "
  #killproc -p "$PIDFILE" -d 300 /usr/bin/mongod
  ps h -o pid -C node | tr '\n' ' ' | xargs sudo kill -9
  RETVAL=$?
  [ -e /var/push.socket ] && rm -f /var/push.socket
  [ $RETVAL -eq 0 ] && { rm -f /var/lock/subsys/pushserverd;success "OK"; }
echo
}

restart () {
    stop
    start
}




ulimit -n 160000
RETVAL=0
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  status)
    status node
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload} "
    RETVAL=1
esac

exit $RETVAL
